# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21952d18b033456c3c958458415d58d9a18349aaef20709dbe664b514091422d60788db9db2b6e6688c79aa72eb57fec7f96f28a8d1c1a94e9e5b96e28bb2419

test:
  secret_key_base: 0bf1b6be0a31847aba0268164258c945ff3c105de09225bfa328a8a09127e2a6e0289b23c97672017704d50b805c4cc41bdcd80dfd9157b098a9a80e6de1638a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
